spring.application.name=OFERTA

serve.port=8081
spring.datasource.url=
spring.datasource.username=root
spring.datasource.password=
spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-plataforme=org.hibernate.dialect.MySqQLDialect

spring.jpahibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

